In [1]:
import numpy as np
import nestle
import math

import matplotlib.pyplot as plt
import matplotlib.animation as animation

import corner

from scipy.integrate import quad

from nsdmd import model 
from nsdmd import io

import pandas as pd




In [2]:
data_file = io.get_data_file_path('example_data.txt')
data_file

'/Users/margin/nsdmd/data/example_data.txt'

In [3]:
data_file = io.get_data_file_path('dataref1.txt')
data_file

'/Users/margin/nsdmd/data/dataref1.txt'

In [4]:
data = io.load_data('./data/dataref1.txt')
data

(array([   3.59,    4.51,    5.53,    7.56,    8.34,    6.5 ,    9.45,
          10.5 ,   11.44,   12.51,   13.53,   14.59,   16.05,   18.64,
          26.3 ,   28.26,   29.51,   32.04,   33.99,   36.49,   38.41,
          40.42,   42.4 ,   44.49,   45.99,   48.06,   49.49,   51.39,
          53.89,   56.89,   57.98,   60.92,   64.73,   69.31,   72.96,
          76.95,   81.13,   84.9 ,   89.35,   92.44,   97.41,  100.72,
         106.77,  119.98,  189.49]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 223.11,  247.88,  253.14,  267.8 ,  270.52,  270.95,  235.58,
         249.72,  261.96,  284.3 ,  271.54,  251.43,  320.7 ,  286.46,
         189.64,  237.99,  209.82,  179.14,  170.37,  175.92,  191.57,
         197.59,  192.79,  213.22,  179.39,  213.03,  178.57,  183.31,
         157.89,  191.76,  210.72,  168.02,  206.47,  203.62,  190.53,
         222.72,  186.29,  12

In [5]:
data_file = io.get_data_file_path('dataref1.txt')
data = io.load_data(data_file)
data

(array([   3.59,    4.51,    5.53,    7.56,    8.34,    6.5 ,    9.45,
          10.5 ,   11.44,   12.51,   13.53,   14.59,   16.05,   18.64,
          26.3 ,   28.26,   29.51,   32.04,   33.99,   36.49,   38.41,
          40.42,   42.4 ,   44.49,   45.99,   48.06,   49.49,   51.39,
          53.89,   56.89,   57.98,   60.92,   64.73,   69.31,   72.96,
          76.95,   81.13,   84.9 ,   89.35,   92.44,   97.41,  100.72,
         106.77,  119.98,  189.49]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 223.11,  247.88,  253.14,  267.8 ,  270.52,  270.95,  235.58,
         249.72,  261.96,  284.3 ,  271.54,  251.43,  320.7 ,  286.46,
         189.64,  237.99,  209.82,  179.14,  170.37,  175.92,  191.57,
         197.59,  192.79,  213.22,  179.39,  213.03,  178.57,  183.31,
         157.89,  191.76,  210.72,  168.02,  206.47,  203.62,  190.53,
         222.72,  186.29,  12

In [6]:
# NewModel.results_NFW (loglike_NFW, prior_transform_NFW,'filename' ,[a,b])  # a,b limits prior  
model.sample (model.loglike_NFW, model.prior_transform_NFW, 'dataref1.txt',[10,10E10])

log evidence
-283.187269911
numerical (sampling) error on logz
0.3588349938961697
array of sample parameters
[[  9.86140731e+00   9.63552945e+10]
 [  9.31157866e+00   9.09906843e+10]
 [  8.97720044e+00   9.09750844e+10]
 ..., 
 [  3.26781937e+00   5.67190429e+08]
 [  3.27496368e+00   5.65068208e+08]
 [  3.24086884e+00   5.75661775e+08]]
array of weights associated with each sample
[ 0.          0.          0.         ...,  0.00372225  0.0037447
  0.00292663]


   ncall: 43946
    logl: array([ -1.79786322e+08,  -1.54093824e+08,  -1.44896486e+08, ...,
        -2.69405527e+02,  -2.69399514e+02,  -2.69646004e+02])
 logzerr: 0.3588349938961697
 weights: array([ 0.        ,  0.        ,  0.        , ...,  0.00372225,
        0.0037447 ,  0.00292663])
 samples: array([[  9.86140731e+00,   9.63552945e+10],
       [  9.31157866e+00,   9.09906843e+10],
       [  8.97720044e+00,   9.09750844e+10],
       ..., 
       [  3.26781937e+00,   5.67190429e+08],
       [  3.27496368e+00,   5.65068208e+08],
       [  3.24086884e+00,   5.75661775e+08]])
   niter: 1477
       h: 12.876255284446415
  logvol: array([ -4.61016602,  -4.62016602,  -4.63016602, ..., -19.37517019,
       -19.37517019, -19.37517019])
    logz: -283.18726991137504